### ISSUE TITLE
Hello, I'm a novice. I can't understand what you mean in the document.

### ISSUE THREAD

**Issue by LymanLiuChina** [deontaljaard/mrcnn-docker#1]
At present, I'm learning how to deploy mrcnn to the server. I'm interested in the source code you published, but I don't know how to operate it. Could you tell me in detail how to operate it? If possible, Could you provide a complete source code? Thank you!!

**Comment by deontaljaard** [comment]
@LymanLiuChina thank you for your interest. I, however, am not the author and publisher of the original code. If you wish to understand how to use it, I recommend familiarizing yourself with the source project - [Mask_RCNN](https://github.com/matterport/Mask_RCNN). There's a [notebook](https://github.com/matterport/Mask_RCNN/blob/master/samples/demo.ipynb) there that'll get you started in no time. All the best!
